name: com.jyhong.stock_game
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  shared_preferences: ^2.2.2
  uuid: ^4.0.0
  http: ^1.3.0
  fl_chart: ^0.71.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.3
  logger: ^2.5.0
  google_mobile_ads: ^6.0.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # 여기에 경로 적기
