name: Flutter Build APK and Release

on:
  workflow_dispatch:  # 수동 실행

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: false

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (release + dart-define)
        run: flutter build apk --release --dart-define=BASE_URL=https://stockgame.cc

      - name: Create GitHub Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: v1.0.${{ github.run_number }}  # 자동 버전 이름 (v1.0.1, v1.0.2, ...)
          name: Release v1.0.${{ github.run_number }}
          generate_release_notes: true
