name: Flutter Build APK (Manual Deployment)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'  # ✅ 네 로컬 버전에 맞춰줌
          channel: 'stable'
          cache: false  # ✅ 캐시 비활성화해서 항상 새로 설치

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (release + dart-define)
        run: flutter build apk --release --dart-define=BASE_URL=https://api.stockgame.cc

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
